<?php

namespace App\Http\Controllers;

use App\Models\Server;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ServerController extends Controller
{
    public function index()
    {
        $servers = Server::with('latestMetric')
            ->orderBy('status')
            ->orderBy('name')
            ->paginate(15);

        return view('servers.index', compact('servers'));
    }

    public function create()
    {
        return view('servers.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'hostname' => 'nullable|string|max:255',
            'ip_address' => 'required|ip',
            'location' => 'nullable|string|max:255',
            'provider' => 'nullable|string|max:255',
            'os' => 'nullable|string|max:255',
            // SSH Access
            'ssh_username' => 'nullable|string|max:255',
            'ssh_password' => 'nullable|string|max:255',
            'ssh_port' => 'nullable|integer|min:1|max:65535',
            'ssh_private_key' => 'nullable|string',
            // Panel Access
            'panel_type' => 'nullable|in:aaPanel,cPanel,DirectAdmin,Plesk,Custom,None',
            'panel_url' => 'nullable|string|max:255',
            'panel_username' => 'nullable|string|max:255',
            'panel_password' => 'nullable|string|max:255',
            'panel_port' => 'nullable|integer|min:1|max:65535',
        ]);

        // API token will be auto-generated by model boot method
        $server = Server::create($validated);

        return redirect()
            ->route('servers.show', $server)
            ->with('success', 'Server berhasil ditambahkan! Copy API Token untuk install agent.');
    }

    public function show(Server $server)
    {
        $server->load(['latestMetric', 'websites', 'alerts' => function ($query) {
            $query->where('is_resolved', false)->latest()->take(5);
        }]);

        // Get metrics history (last 24 hours)
        $metricsHistory = $server->metrics()
            ->where('recorded_at', '>=', now()->subDay())
            ->orderBy('recorded_at', 'asc')
            ->get();

        return view('servers.show', compact('server', 'metricsHistory'));
    }

    public function edit(Server $server)
    {
        return view('servers.edit', compact('server'));
    }

    public function update(Request $request, Server $server)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'hostname' => 'nullable|string|max:255',
            'ip_address' => 'required|ip',
            'location' => 'nullable|string|max:255',
            'provider' => 'nullable|string|max:255',
            'os' => 'nullable|string|max:255',
            // SSH Access
            'ssh_username' => 'nullable|string|max:255',
            'ssh_password' => 'nullable|string|max:255',
            'ssh_port' => 'nullable|integer|min:1|max:65535',
            'ssh_private_key' => 'nullable|string',
            // Panel Access
            'panel_type' => 'nullable|in:aaPanel,cPanel,DirectAdmin,Plesk,Custom,None',
            'panel_url' => 'nullable|string|max:255',
            'panel_username' => 'nullable|string|max:255',
            'panel_password' => 'nullable|string|max:255',
            'panel_port' => 'nullable|integer|min:1|max:65535',
        ]);

        // Don't update password fields if empty (keep existing)
        if (empty($validated['ssh_password'])) {
            unset($validated['ssh_password']);
        }
        if (empty($validated['ssh_private_key'])) {
            unset($validated['ssh_private_key']);
        }
        if (empty($validated['panel_password'])) {
            unset($validated['panel_password']);
        }

        $server->update($validated);

        return redirect()
            ->route('servers.show', $server)
            ->with('success', 'Server berhasil diupdate!');
    }

    public function destroy(Server $server)
    {
        $serverName = $server->name;
        $server->delete();

        return redirect()
            ->route('servers.index')
            ->with('success', "Server '{$serverName}' berhasil dihapus!");
    }

    public function regenerateToken(Server $server)
    {
        $server->update([
            'api_token' => Str::random(64)
        ]);

        return back()->with('success', 'API Token berhasil di-generate ulang!');
    }
}
